# Generated by Django 4.0.8 on 2022-10-26 09:51

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 26, 9, 51, 24, 599409))),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('discount', models.PositiveSmallIntegerField(blank=True, help_text='discount percents off', null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('N', 'New'), ('P', 'Paid'), ('S', 'Shipped'), ('C', 'Canceled')], default='N', max_length=1)),
            ],
        ),
    ]
